package com.google.firebase.firestore.local;

import com.google.firebase.firestore.model.BasePath;
import com.google.firebase.firestore.model.ResourcePath;
import com.google.firebase.firestore.util.Assert;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

abstract class d {
    private static List a(String str) {
        int length = str.length();
        Assert.hardAssert(length >= 2, "Invalid path \"%s\"", str);
        if (length == 2) {
            Assert.hardAssert(str.charAt(0) == 1 && str.charAt(1) == 1, "Non-empty path \"%s\" had length 2", str);
            return Collections.emptyList();
        }
        int length2 = str.length() - 2;
        ArrayList arrayList = new ArrayList();
        StringBuilder sb2 = new StringBuilder();
        int i10 = 0;
        while (i10 < length) {
            int indexOf = str.indexOf(1, i10);
            if (indexOf < 0 || indexOf > length2) {
                throw new IllegalArgumentException("Invalid encoded resource path: \"" + str + "\"");
            }
            int i11 = indexOf + 1;
            char charAt = str.charAt(i11);
            if (charAt == 1) {
                String substring = str.substring(i10, indexOf);
                if (sb2.length() != 0) {
                    sb2.append(substring);
                    substring = sb2.toString();
                    sb2.setLength(0);
                }
                arrayList.add(substring);
            } else if (charAt == 16) {
                sb2.append(str.substring(i10, indexOf));
                sb2.append(0);
            } else if (charAt == 17) {
                sb2.append(str.substring(i10, i11));
            } else {
                throw new IllegalArgumentException("Invalid encoded resource path: \"" + str + "\"");
            }
            i10 = indexOf + 2;
        }
        return arrayList;
    }

    static ResourcePath b(String str) {
        return ResourcePath.fromSegments(a(str));
    }

    static String c(BasePath basePath) {
        StringBuilder sb2 = new StringBuilder();
        int length = basePath.length();
        for (int i10 = 0; i10 < length; i10++) {
            if (sb2.length() > 0) {
                e(sb2);
            }
            d(basePath.getSegment(i10), sb2);
        }
        e(sb2);
        return sb2.toString();
    }

    private static void d(String str, StringBuilder sb2) {
        int length = str.length();
        for (int i10 = 0; i10 < length; i10++) {
            char charAt = str.charAt(i10);
            if (charAt == 0) {
                sb2.append(1);
                charAt = 16;
            } else if (charAt == 1) {
                sb2.append(1);
                charAt = 17;
            }
            sb2.append(charAt);
        }
    }

    private static void e(StringBuilder sb2) {
        sb2.append(1);
        sb2.append(1);
    }

    static String f(String str) {
        StringBuilder sb2 = new StringBuilder(str);
        int length = sb2.length() - 1;
        char charAt = sb2.charAt(length);
        Assert.hardAssert(charAt == 1, "successor may only operate on paths generated by encode", new Object[0]);
        sb2.setCharAt(length, (char) (charAt + 1));
        return sb2.toString();
    }
}
